### ISSUE TITLE
Thrust/Drive and FTL values lost on loading saved ship

### ISSUE THREAD

**Issue by Voltschrat** [Perlkonig/ftShipBuilder#1]
for some reason loading a saved ship doesn't correctly set the Thrust rating - it will remain whatever it was set to before loading,  looking like the values aren't being set on load on the site.

loading from JSON or storage doesn't seem to make a difference.

**Comment by Voltschrat** [comment]
steps to reproduce:
A)
   1. Save a ship,
   2. change the values/settings for Thrusters/FTL
   3. re-load the saved ship
  The values are unchanged, and are still the same as in step 2.

B)
   1. Refresh site, clearing cache, starting from a blank state.
   2. select random options for thrust rating and drives
   3. load a previously saved ship
   The values are unchanged by the loading process, and are the same as in step 2.

**Comment by Perlkonig** [comment]
It also affects FTL. The values get saved but not loaded. Looking into it.

**Comment by Perlkonig** [comment]
Corrected. v1.0.1 pushed.
