### ISSUE TITLE
Base cost of hull

### ISSUE THREAD

**Issue by mandalon** [Perlkonig/ftShipBuilder#7]
First of all, thanks for your efforts, this is a great piece of work.

However, the ship cost are missing the "base hull cost" of <mass> points, in addition to the cost for the integrity boxes.
At the moment, it seems that the NPV are calculated based on the hull integrity whereas the CPV are calculated based on the ship's mass. It should always be both.

For example, a ship of 32 mass with 12 hull points should cost

32 x 1 + 12 x 2 = 56 (NPV)
or 
32 x 32 / 100 + 12 x 2 = 34 (CPV)

but instead it costs only 24 (NPV) or 10 (CPV) which is the hull integrity cost (but no basic hull cost) for NPV and the correct basic hull cost for CPV (but no hull integrity cost) for CPV.

**Comment by Perlkonig** [comment]
Thank you for this! I'm not sure how I missed that first row of the table in section 14.1! Can you tell I haven't played in a very, very long time? :) I will get this fixed as soon as I can.

**Comment by Perlkonig** [comment]
v2.2.2 fixes the issue. Thanks again for the report.
